<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>kestrel-server</AssemblyName>
    <RootNamespace>KestrelCache.Server</RootNamespace>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../KestrelCache/KestrelCache.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="KestrelCache.Tests" />
  </ItemGroup>

</Project>
