<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>KestrelCache</RootNamespace>
    <AssemblyName>KestrelCache</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="KestrelCache.Tests" />
    <InternalsVisibleTo Include="kestrel-bench" />
  </ItemGroup>

</Project>
